### ISSUE TITLE
Duplication of Widgets

### ISSUE THREAD

**Issue by GCrouspeyre** [Raathigesh/Dazzle#10] opened 2016-11-17 22:46 UTC
Hi,

Really liking this library over react-grid-layout.

However, not sure if it's been picked up before, but it looks like widgets get duplicated if they are dragged and dropped on widgets of the same type.

Will have a look but if it's a know issue, would love to have a fix.

Thanks!

Update: Odd. It seems that:
- The duplication is not consistently occuring
- The duplication can also occur when not dragged over the same type

**Comment by cperera-aud** [comment] 2016-12-06 00:55
I'm also noticing this issue and it can be reproduced with demo site as well (http://raathigesh.com/dazzle/). You have to drag and drop several times before you hit the issue. @Raathigesh do you know why this maybe happening? It would be great if we can get a fix for this.

Thanks in advance.

**Comment by Raathigesh** [comment] 2016-12-06 05:02
I can also reproduce the issue. I will get back to you after doing a bit of digging into this.

**Comment by cperera-aud** [comment] 2016-12-06 05:21
Thanks @Raathigesh

**Comment by cperera-aud** [comment] 2016-12-14 23:06
Hi @Raathigesh sorry to trouble you but I was wondering did you make any progress on the issue? Thanks!

**Comment by Raathigesh** [comment] 2016-12-15 18:14
I'm looking into it but it seems to bit tricky to exactly figure out the reason. The last fix I added also seems to be not working. I will investigate further during the weekend. Could you please update to version 1.2.4 and check whether the issue is still reproducible.

**Comment by cperera-aud** [comment] 2016-12-15 23:55
@Raathigesh I tried out version 1.2.4 and I can't reproduce the widget duplication issue on my end so the fix that you put in looks good. Thank you for taking the time to look into it.

**Comment by Raathigesh** [comment] 2016-12-16 04:13
I'm closing this for now. Feel free to reopen if this issue surfaces again.

**Closed by Raathigesh** 2016-12-16 04:13 UTC
